GET http://localhost:8000/products/ HTTP/1.1

### 

GET http://localhost:8000/products/2/ HTTP/1.1

###
PUT  http://localhost:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwMTA2NDQ5LCJpYXQiOjE3NzAxMDYxNDksImp0aSI6ImFjYTE3OWViMjgwNDQxNDViNGM0NWQ4OGJjYmMyNDdkIiwidXNlcl9pZCI6IjEifQ.WZ-QdDT4PLmCMu83LOra0hWEVD0WZswnQ9PFK5gZVYU

{
  "name":"Television",
  "price": 300.00,
  "stock": 10,
  "description": "Amazing TV with 50' Screen Size"
}

###

DELETE http://localhost:8000/products/8/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwMTA2NDQ5LCJpYXQiOjE3NzAxMDYxNDksImp0aSI6ImFjYTE3OWViMjgwNDQxNDViNGM0NWQ4OGJjYmMyNDdkIiwidXNlcl9pZCI6IjEifQ.WZ-QdDT4PLmCMu83LOra0hWEVD0WZswnQ9PFK5gZVYU

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwMDI3MTc2LCJpYXQiOjE3NzAwMjY4NzYsImp0aSI6IjZhZTdjMmQyMTY4NDRmMzM4OTAyZWFmMzhhNWE1YjRjIiwidXNlcl9pZCI6IjIifQ.FXrmw0cjNNki0_EZhWpM2Es4F1zHANwt6NqrRR9NHdo

{
  "name":"Television",
  "price": 300.00,l
  "stock": 10,
  "description": "Amazing TV"
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
  "username":"zaindotdev",
  "password": 9246
}

###

GET http://localhost:8000/orders/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwODAyMDM4LCJpYXQiOjE3NzA4MDE3MzgsImp0aSI6IjU5MWM2MDdhZWY1YTQ1NGNiMDgzN2M1YzlmZWY2MmVjIiwidXNlcl9pZCI6IjEifQ.ufuu19_bi03-DdEKaClWJtOSYqouC7Xrz9d4hjH0jvw

###
GET http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMTM1MjA2LCJpYXQiOjE3NzExMzQ5MDYsImp0aSI6IjM4MzlhNThlYzQ1MTRhMTk5NWI5YjM4OGUyMWMyNDRkIiwidXNlcl9pZCI6IjEifQ.Hd2omJTbn0pQYOI0AdcNKHNPpczLoZfPO-au08G8DSA

###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDE4OTgyMiwiaWF0IjoxNzcwMTAzNDIyLCJqdGkiOiI0NjYxZTVlZTQ5NDI0YTExOTkzOWM2MjYyNDFkMGQ4MSIsInVzZXJfaWQiOiIxIn0.BmbqI7wFsWJ1TPnIj6R11mHk1ADG4ktFPuKSpSL6Xe4"
}

###

POST http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMTQ3MjMxLCJpYXQiOjE3NzExNDM2MzEsImp0aSI6IjE3YjdlYThhMTU0ZTQ4YzdiYjkwMmEyMzZjYzg0YjJkIiwidXNlcl9pZCI6IjYifQ.ujC9sOIJPnOyL3iUuqZcbcdUsnwgim1JDytfdyW7vnM
Content-Type: application/json

{
  "status":"Pending",
  "items":[
    {
      "product": 2, 
      "quantity": 2
    },
    {
      "product": 3, 
      "quantity": 1
    }
  ]
}

###
GET http://localhost:8000/orders/029c188f-0637-42e3-a6f1-7a0854bb2d80/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMTMwNzA0LCJpYXQiOjE3NzExMzA0MDQsImp0aSI6IjhjYTg1Mjg4OWY3NDQ0YjRiYzkwNmM2ODdhNDFlZDViIiwidXNlcl9pZCI6IjYifQ.5jyhg6zpcBRfqKPG9G5GhSCmPX5jjOANhSsIOXJd2yI

###
PUT http://localhost:8000/orders/029c188f-0637-42e3-a6f1-7a0854bb2d80/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMTMwMjQ1LCJpYXQiOjE3NzExMjk5NDUsImp0aSI6ImIxOTZhODM4MWY4OTRjYjJiNGVlYmY4OTgwMTg2ODUwIiwidXNlcl9pZCI6IjYifQ.fBhhUmVolYwR7AOmYi_XdQytVNZAJEMsMumcd-LN17w

{
  "status": "Pending", 
  "items": [ 
    {
      "product": 2, 
        "quantity": 1
    },
    {
      "product": 3, 
      "quantity": 0
    }
  ]
}

###
DELETE http://localhost:8000/orders/029c188f-0637-42e3-a6f1-7a0854bb2d80/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMTMwMjQ1LCJpYXQiOjE3NzExMjk5NDUsImp0aSI6ImIxOTZhODM4MWY4OTRjYjJiNGVlYmY4OTgwMTg2ODUwIiwidXNlcl9pZCI6IjYifQ.fBhhUmVolYwR7AOmYi_XdQytVNZAJEMsMumcd-LN17w
