GET http://localhost:8000/products/ HTTP/1.1

### 

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwMDI3MTc2LCJpYXQiOjE3NzAwMjY4NzYsImp0aSI6IjZhZTdjMmQyMTY4NDRmMzM4OTAyZWFmMzhhNWE1YjRjIiwidXNlcl9pZCI6IjIifQ.FXrmw0cjNNki0_EZhWpM2Es4F1zHANwt6NqrRR9NHdo

{
  "name":"Television",
  "price": 300.00,
  "stock": 10,
  "description": "Amazing TV"
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
  "username":"zaindotdev",
  "password": 9246
}